on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: a job testing file transfer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Transfer file
        uses: ./
        id: transfer
        with:
          file-to-transfer: 'entrypoint.sh'
          url-to-transfer-to: 'https://installables.stonemountain.dk/installables/{instId}/downloadables/{downId}'
          query-param-with-size: 'size'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"